version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\gopasspw\gopass

environment:
  GOPATH: c:\gopath
  GOPASS_BINARY: c:\gopath\src\github.com\gopasspw\gopass\gopass.exe

init:
  - git config --global user.email "gopass@gopass.pw"
  - git config --global user.name "Gopass"
  - git config --global core.safecrlf false

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - ps: appveyor-retry choco install make gnupg

build_script:
  - ps: go.exe mod download
  - make travis-windows
  - test-integration

