language: go
dist: trusty

jobs:
  allow_failures:
    - os: windows
  include:
    - os: windows
      env: SLOW_TEST_FACTOR=100 BUILDFLAGS='' GOPASS_OUTPUT=gopass.exe
    - os: osx
      env: SLOW_TEST_FACTOR=100
    - os: linux

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install git gnupg2 clang-format-3.9; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install git gnupg clang-format || true; fi
  - | 
      if [ $TRAVIS_OS_NAME = windows ]; then 
      choco install --yes --force --debug make gnupg || true; 
      rm /usr/bin/gpg
      diskperf -y
      fi
  - git config --global user.name nobody
  - git config --global user.email foo.bar@example.org

go:
  - '1.14.x'

script:
  - ./travis_helper.sh travis
  - make test-integration
  - make install-completion

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage-all.out
