language: go
dist: trusty
os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install git gnupg2; else brew install git gnupg; fi

go:
  - 1.9

script:
  - make all
  - make test-integration
  - make install-completion

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage-all.out
