language: go
dist: trusty
os:
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install git gnupg2; else brew install git gnupg || true; fi
  - git config --global user.name nobody
  - git config --global user.email foo.bar@example.org

go:
  - '1.10'

script:
  - make travis
  - make test-integration
  - make install-completion

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage-all.out
