language: go

go:
  - 1.8.x

sudo: required
before_install:
  - go get -v github.com/golang/lint/golint
  - sudo apt-get update -qq
  - sudo apt-get install -y libcrack2-dev

after_success:
  - gem install fpm
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

script:
  - make clean
  - make vet
  - make lint
  - make errcheck
  - make test
  - make build
  - make test-integration
